// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function ClearToken() {
  return window['go']['main']['App']['ClearToken']();
}

export function DownloadAllAudio() {
  return window['go']['main']['App']['DownloadAllAudio']();
}

export function DownloadPlaylist(arg1) {
  return window['go']['main']['App']['DownloadPlaylist'](arg1);
}

export function DownloadTrack(arg1) {
  return window['go']['main']['App']['DownloadTrack'](arg1);
}

export function GetSavePath() {
  return window['go']['main']['App']['GetSavePath']();
}

export function HasValidToken() {
  return window['go']['main']['App']['HasValidToken']();
}

export function SaveToken(arg1) {
  return window['go']['main']['App']['SaveToken'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
