// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload():Promise<void>;

export function ClearToken():Promise<void>;

export function DownloadAllAudio():Promise<void>;

export function DownloadPlaylist(arg1:string):Promise<void>;

export function DownloadTrack(arg1:string):Promise<void>;

export function GetSavePath():Promise<string>;

export function HasValidToken():Promise<boolean>;

export function SaveToken(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;
