// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function CancelDownload():Promise<void>;

export function CheckPlaylistLocalProgress(arg1:string):Promise<number>;

export function ClearToken():Promise<void>;

export function DownloadAllAudio():Promise<void>;

export function DownloadPlaylist(arg1:string):Promise<void>;

export function DownloadTrack(arg1:string):Promise<void>;

export function DownloadUserPlaylist(arg1:number,arg2:string):Promise<void>;

export function GetSavePath():Promise<string>;

export function GetUserPlaylists():Promise<Array<api.Playlist>>;

export function HasValidToken():Promise<boolean>;

export function OpenAuthPage():Promise<void>;

export function OpenPlaylistFolder(arg1:string):Promise<void>;

export function ParseAndSaveUrlToken(arg1:string):Promise<void>;

export function SaveToken(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;
